### ISSUE TITLE
./litehtml does not contain CMakeLists.txt

### ISSUE THREAD

**Issue by WandertVanDerHertz** [litehtml/litebrowser-linux#3]
When I run cmake ~/litebrowser-linux/ I get this error:

```
CMake Error at CMakeLists.txt:27 (add_subdirectory):
  The source directory

    /home/kali/litebrowser-linux/litehtml

  does not contain a CMakeLists.txt file.

```
I'm not used to use cmake (./configure && make && make install often works just fine). So i don't know if I'm doing something wrong. How could I fix this?

Here would be the entire log of the output: 
http://sprunge.us/hhME

**Comment by tordex** [comment]
Please check if the folder /home/kali/litebrowser-linux/litehtml have litehtml sources. Note you have to add ```--recursive``` option to fill _litehtml_ folder because it is added to git as submodule.

**Comment by WandertVanDerHertz** [comment]
Oh, you were right. Thanks. But now I get this error:

```
[  2%] Building C object CMakeFiles/litehtml.dir/src/gumbo/attribute.c.o
/home/tux/litehtml/src/gumbo/attribute.c: In function ‘gumbo_get_attribute’:
/home/tux/litehtml/src/gumbo/attribute.c:30:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (unsigned int i = 0; i < attributes->length; ++i) {
   ^
/home/tux/litehtml/src/gumbo/attribute.c:30:3: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
CMakeFiles/litehtml.dir/build.make:882: recipe for target 'CMakeFiles/litehtml.dir/src/gumbo/attribute.c.o' failed
make[2]: *** [CMakeFiles/litehtml.dir/src/gumbo/attribute.c.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/litehtml.dir/all' failed
make[1]: *** [CMakeFiles/litehtml.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

```

I've tried things such as `cmake -Dstd=c99` and `export CC=99` neither did work. What should I do?

**Comment by tordex** [comment]
The problem in the build type. It is not selected by default and have to add option ```-DCMAKE_BUILD_TYPE=RELEASE``` into cmake command.  I've pushed update in the CMakeLists.txt to select Release by default.

**Comment by WandertVanDerHertz** [comment]
Ok thanks. It works now. Nice project what you've got here :) .
