### ISSUE TITLE
Poco/URI.h: No such file or directory

### ISSUE THREAD

**Issue by EkanshdeepGupta** [litehtml/litebrowser-linux#4]
I ran `git clone --recursive https://github.com/litehtml/litebrowser-linux.git` to clone this repository. I then ran `cmake ./`, and finally `make`.

On running make, around the 90% mark, I'm getting this error:

[ 87%] Building C object litehtml/CMakeFiles/litehtml.dir/src/gumbo/vector.c.o
Linking CXX static library liblitehtml.a
[ 87%] Built target litehtml
[ 88%] Generating src/master.css.inc
Scanning dependencies of target litebrowser
[ 90%] Building CXX object CMakeFiles/litebrowser.dir/src/main.cpp.o
In file included from /home/ekansh/Downloads/litebrowser-linux/src/main.cpp:1:0:
/home/ekansh/Downloads/litebrowser-linux/src/globals.h:26:22: fatal error: Poco/URI.h: No such file or directory
 #include <Poco/URI.h>
                      ^
compilation terminated.
make[2]: *** [CMakeFiles/litebrowser.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/litebrowser.dir/all] Error 2
make: *** [all] Error 2

How should I proceed to fix this issue?

**Comment by tordex** [comment]
litebrowser for Linux is required [POCO C++ Libraries](https://pocoproject.org/)

**Comment by EkanshdeepGupta** [comment]
Thanks a lot!

**Comment by drizt** [comment]
Please, add POCO checking  to CMakeLists.txt.

**Comment by kizerkizer** [comment]
Please add POCO to the list of dependencies / edit CMakeLists.txt. I ran into the same issue.

For those wondering, I installed poco on M1 Mac with `brew install poco`, the added the following to CMakeLists.txt and it compiled successfully: 
`
link_directories("/opt/homebrew/lib")
include_directories("/opt/homebrew/include")
`
